### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by rehno-lindeque** [gdotdesign/elm-ui-website#8]
Hi, I see the `elm-package.json` file indicates a BSD3 license, but there's no `LICENSE` file accompanying the source code.

Would it be possible to add one?

**Comment by gdotdesign** [comment]
Thanks for letting me know, I added it: https://github.com/gdotdesign/elm-ui-website/blob/master/LICENSE.md

**Comment by rehno-lindeque** [comment]
Thank you! This looks like a *really* slick way to document your widgets...

**Comment by rehno-lindeque** [comment]
PS, I wonder if you've considered extracting an elm documentation framework? I haven't had a chance yet to look at how this works.

**Comment by gdotdesign** [comment]
This could be generalized up to a point like the form (on the right side of the demo), the documentation rendering and the list on the right, however there is boilerplate for each widget / component https://github.com/gdotdesign/elm-ui-website/tree/master/source/Reference which is a downside to consider.
